version: "3.9"

services:
  mssql:
    build:
      context: ./
      dockerfile: database.Dockerfile
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassw0rd
    ports:
      - '1433:1433'
